version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pkr-postgres
    environment:
      POSTGRES_DB: pkr-management-system
      POSTGRES_USER: pkr
      POSTGRES_PASSWORD: pkr1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
